# Generated by Django 4.2.6 on 2023-11-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_measure_slug_alter_recipe_category_alter_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
