# Generated by Django 4.2.6 on 2023-11-16 18:48

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='slug',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='posts/rank3.jpg', upload_to=backend_api.models.upload_to, verbose_name='Image'),
        ),
    ]
