# Generated by Django 4.2.6 on 2023-11-16 19:02

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_remove_comments_slug_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=backend_api.models.upload_to, verbose_name='Image'),
        ),
    ]
