# Generated by Django 4.2.6 on 2023-11-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_rating_starrating_alter_recipe_image_delete_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StarRating',
        ),
    ]
