# Generated by Django 4.2.6 on 2023-12-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_ban'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ban',
        ),
    ]
