# Generated by Django 4.2.6 on 2023-12-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0021_ban_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='slug',
        ),
    ]
