# Generated by Django 4.2.6 on 2023-12-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0022_remove_ban_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
    ]
