# Generated by Django 4.2.6 on 2023-12-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0023_alter_recipe_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
    ]
