# Generated by Django 4.2.6 on 2023-12-19 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0024_alter_recipe_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='id',
        ),
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
