# Generated by Django 4.2.6 on 2023-12-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0026_remove_user_is_banned_category_user_cousin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='slug',
        ),
    ]
